import { validateUser } from 'chums-local-modules';
import { validateAdmin } from '../../common.js';
import { Router } from "express";
import { delCategory, delCategoryItem, getCategories, getCategory, getCategoryItems, postCategory, postCategoryItem, postItemSort } from './category.js';
import { delVariant, getProduct, getProductList, getVariant, getVariantsList, postProduct, postSetDefaultVariant, postVariant, postVariantSort } from './product.js';
import { getProductItems } from './item.js';
import { delImage, getImage, getImages, postImage } from './images.js';
import { getSeason, getSeasons, postSeason } from './seasons.js';
import { delMixItem, getMix, getSageBOM, postMix, postMixItems } from './mix.js';
import { getCategoryUsage } from "./category-items.js";
const router = Router();
router.get('/category/list.json', getCategories);
router.get('/category/list', getCategories);
router.get('/category/id/:id.json', getCategory);
router.get('/category/usage/:keyword.json', getCategoryUsage);
router.get('/category/:keyword.json', getCategory);
router.get('/category/:parentId/children.json', getCategories);
router.get('/category/:parentId/items.json', getCategoryItems);
router.get('/category/:parentId/items/:id.json', getCategoryItems);
router.post('/category.json', validateUser, validateAdmin, postCategory);
router.post('/category/item.json', validateUser, validateAdmin, postCategoryItem);
router.post('/category/:parentId/sort.json', validateUser, validateAdmin, postItemSort);
router.delete('/category/:id.json', validateUser, validateAdmin, delCategory);
router.delete('/category/item/:id.json', validateUser, validateAdmin, delCategoryItem);
router.get('/image/:id.json', getImage);
router.post('/images.json', validateUser, validateAdmin, postImage);
router.post('/image.json', validateUser, validateAdmin, postImage);
router.get('/images/:productId.json', getImages);
router.put('/images/:id.json', validateUser, validateAdmin, postImage);
router.delete('/image/:productId/:id.json', validateUser, validateAdmin, delImage);
router.get('/id/:id.json', getProduct);
router.get('/keyword/:keyword.json', getProduct);
router.get('/items/:productId.json', getProductItems);
router.post('/:id.json', validateUser, validateAdmin, postProduct);
router.put('/:id.json', validateUser, validateAdmin, postProduct);
router.get('/list.json', getProductList);
// router.get('/products/:keyword')
router.get('/mix/:productId.json', getMix);
router.get('/mix/:productId/bom.json', validateUser, validateAdmin, getSageBOM);
router.post('/mix/:productId/:mixID/items.json', validateUser, validateAdmin, postMixItems);
router.post('/mix/:productId.json', validateUser, validateAdmin, postMix);
router.put('/mix/:productId/:mixID.json', validateUser, validateAdmin, postMix);
router.delete('/mix/:productId/:mixID/:id.json', validateUser, validateAdmin, delMixItem);
router.get('/seasons.json', getSeasons);
router.get('/seasons/:code.json', getSeason);
router.post('/seasons/:id.json', validateUser, validateAdmin, postSeason);
router.get('/variants/:productId.json', getVariantsList);
router.get('/variants/:productId/:id.json', getVariant);
router.post('/variants/:productId.json', validateUser, validateAdmin, postVariant);
router.put('/variants/:productId/sort.json', validateUser, validateAdmin, postVariantSort);
router.put('/variants/:productId/:id.json', validateUser, validateAdmin, postVariant);
router.put('/variants/:productId/:id/default.json', validateUser, validateAdmin, postSetDefaultVariant);
router.delete('/variants/:productId/:id.json', validateUser, validateAdmin, delVariant);
export default router;
