CREATE TABLE `products` (
  `products_id` int(11) NOT NULL AUTO_INCREMENT,
  `products_quantity` int(4) NOT NULL,
  `products_model` varchar(45) DEFAULT NULL,
  `products_keyword` varchar(64) DEFAULT NULL,
  `products_image` varchar(64) DEFAULT NULL,
  `products_price` decimal(15,4) NOT NULL,
  `products_date_added` datetime NOT NULL,
  `products_last_modified` datetime DEFAULT NULL,
  `products_date_available` varchar(50) DEFAULT NULL,
  `products_weight` decimal(5,2) NOT NULL,
  `products_status` tinyint(1) NOT NULL,
  `products_is_apparel` tinyint(1) NOT NULL DEFAULT '0',
  `products_in_google_merchant_feed` tinyint(1) NOT NULL DEFAULT '1',
  `products_tax_class_id` int(11) NOT NULL,
  `manufacturers_id` int(11) DEFAULT NULL,
  `products_ordered` int(11) NOT NULL DEFAULT '0',
  `materials_id` int(11) NOT NULL DEFAULT '0',
  `products_sell_as` int(11) NOT NULL DEFAULT '1',
  `urlcomponent` varchar(1023) NOT NULL DEFAULT '',
  `products_upc` varchar(32) DEFAULT '',
  `google_product_category` text,
  `products_category` text,
  `products_color_text` varchar(1023) NOT NULL DEFAULT '',
  `products_default_color` varchar(45) NOT NULL DEFAULT '100',
  `default_categories_id` int(11) NOT NULL DEFAULT '0',
  `default_parent_products_id` int(11) NOT NULL DEFAULT '0',
  `options` varchar(1023) NOT NULL DEFAULT '[]',
  `required_options` varchar(1023) NOT NULL DEFAULT '[]',
  `can_dome` int(1) DEFAULT NULL,
  `can_screen_print` int(1) DEFAULT NULL,
  `available_for_sale` int(1) NOT NULL DEFAULT '1',
  `timestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`products_id`),
  UNIQUE KEY `products_keyword_UNIQUE` (`products_keyword`),
  KEY `idx_products_model` (`products_model`),
  KEY `idx_products_date_added` (`products_date_added`)
) ENGINE=MyISAM AUTO_INCREMENT=761 DEFAULT CHARSET=utf8;