import { Router } from 'express';
import Debug from 'debug';
import { default as productRouter } from './product/index.js';
import { getKeyword, getKeywords } from './keywords/index.js';
import { delPage, getPage, getPages, postPage } from './pages/index.js';
import { default as menuRouter } from './menus/index.js';
import { getCurrentMessages, getMessage, getMessages, postMessage } from './site-messages/index.js';
import { formattedState, preloadJS } from './preload.js';
import { getErrors, postError } from './error-reporting/index.js';
import { getActiveSlides, getSlides } from "./features/slides.js";
import { getSearch3, getSearch3b } from './search/search-v3.js';
import { validateAdmin } from "./common.js";
import { delBanner, getActiveBanners, getBanners, postBanner } from "./features/banners.js";
import { validateUser } from "chums-local-modules";
import { aboutAPI } from "./about/index.js";
import cartsRouter from "./carts/index.js";
import { getProductImageValidation, renderProductImageValidationTable } from "./validation/product-images.js";
import { getPreloadedStateV2, getPreloadedStateV2js } from "./preloaded-state/v2.js";
import { cookieConsentHelper, getCookieConsent, postCookieConsent } from "cookie-consent";
import { getCookieConsentInfo } from "./cookie-consent/index.js";
import { getPreloadedStateV2a, renderPreloadedStateV2a } from "./preloaded-state/v2-1.js";
const debug = Debug('chums:lib:index');
const router = Router();
const debugLogger = (req, res, next) => {
    debug(req.ip, req.method, req.originalUrl, req.get('referrer') || req.get('host'));
    next();
};
router.use(debugLogger, cookieConsentHelper);
router.get('/about.json', aboutAPI);
router.use('/carts', cartsRouter);
router.get('/cookie-consent.json', getCookieConsent);
router.get('/cookie-consent/info.json', getCookieConsentInfo);
router.post('/cookie-consent.json', postCookieConsent);
// used with B2B website
router.post('/error-reporting', postError);
router.get('/error-reporting.json', validateUser, validateAdmin, getErrors);
// router.use('/features', features.router);
router.get('/features/slides/:id.json', getSlides);
router.get('/features/slides/active.json', getActiveSlides);
router.get('/features/banners/active.json', getActiveBanners);
router.get('/features/banners/:id.json', validateUser, validateAdmin, getBanners);
router.get('/features/banners/all.json', validateUser, validateAdmin, getBanners);
router.post('/features/banners.json', validateUser, validateAdmin, postBanner);
router.put('/features/banners/:id.json', validateUser, validateAdmin, postBanner);
router.delete('/features/banners/:id.json', validateUser, validateAdmin, delBanner);
router.get('/keywords.json', getKeywords);
router.get('/keywords/:keyword.json', getKeyword);
router.use('/menus', menuRouter);
router.get('/messages.json', getCurrentMessages);
router.get('/messages/list.json', validateUser, validateAdmin, getMessages);
router.get('/messages/:id.json', validateUser, validateAdmin, getMessage);
router.post('/messages.json', validateUser, validateAdmin, postMessage);
router.get('/preload/v2/state.json', getPreloadedStateV2);
router.get('/preload/v2a/state.json', getPreloadedStateV2a);
router.get('/preload/v2/state.js', getPreloadedStateV2js);
router.get('/preload/v2a/state.js', renderPreloadedStateV2a);
router.get('/preload/state.json', formattedState);
router.get('/preload/state.js', preloadJS);
router.use('/products', productRouter);
router.get('/search.json', getSearch3b);
router.get('/search/v3/:term', getSearch3);
router.get('/pages.json', validateUser, validateAdmin, getPages);
router.get('/pages/id/:id.json', validateUser, validateAdmin, getPage);
router.get('/pages/:keyword.json', getPage);
router.post('/pages.json', validateUser, validateAdmin, postPage);
router.put('/pages/:id.json', validateUser, validateAdmin, postPage);
router.delete('/pages/:id.json', validateUser, validateAdmin, delPage);
router.get('/validate/product/images.json', validateUser, validateAdmin, getProductImageValidation);
router.get('/validate/product/images.html', validateUser, validateAdmin, renderProductImageValidationTable);
export default router;
